### ISSUE TITLE
之前可以用 最近突出出现的这个bug

### ISSUE THREAD

**Issue by wxs846521** [treadpit/wx_calendar#121]
jsEnginScriptError
Cannot read property '__wxspec__' of null
TypeError: Cannot read property '__wxspec__' of null
    at h (http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:13758)
    at e.value (http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:15394)
    at a._updateCb (http://127.0.0.1:60063/appservice/__dev__/WAService.js:11:13147)
    at a.doUpdates (http://127.0.0.1:60063/appservice/__dev__/WAService.js:10:23310)
    at t.applyProperties (http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:23905)
    at e.value (http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:17931)
    at http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:18003
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:17975)
    at e.value (http://127.0.0.1:60063/appservice/__dev__/WAService.js:12:14921)

**Comment by treadpit** [comment]
`wxspec ` 这个不是日历组件里面的属性，建议排查其他业务逻辑
