### ISSUE TITLE
无法实现跳转到当前的日期

### ISSUE THREAD

**Issue by FlyThink-ing** [treadpit/wx_calendar#16]
跳转的方法，可以触发，但是无法实现跳转的功能

**Comment by treadpit** [comment]
@FlyThink-ing 感谢反馈，已修复 🌿

**Comment by keyworldtony** [comment]
未修复，
  jump() {
    // jump(2019, 5, 3);
    jumpToToday();
    // jump()
    console.log("jump========",getSelectedDay());
  },

thirdScriptError
(0 , _main.jumpToToday) is not a function; [Component] Event Handler Error @ pages/calendarComponent/index#bound jump
TypeError: (0 , _main.jumpToToday) is not a function
    at z.jump (http://127.0.0.1:40519/appservice/pages/calendarComponent/index.js:52:27)
    at Object.r.safeCallback (http://127.0.0.1:40519/appservice/__dev__/WAService.js:1:746848)
    at http://127.0.0.1:40519/appservice/__dev__/WAService.js:1:887706
    at f (http://127.0.0.1:40519/appservice/__dev__/WAService.js:1:890945)
    at http://127.0.0.1:40519/appservice/__dev__/WAService.js:1:890219
    at n (http://127.0.0.1:40519/appservice/__dev__/WAService.js:1:214148)
    at e (http://127.0.0.1:40519/appservice/appservice?t=1553521122037:1488:20972)
    at r.registerCallback.t (http://127.0.0.1:40519/appservice/appservice?t=1553521122037:1488:21157)
    at l.forEach.t (http://127.0.0.1:40519/appservice/appservice?t=1553521122037:1488:1581)
    at Array.forEach (<anonymous>)

**Comment by treadpit** [comment]
@keyworldtony 请仔细阅读文档，没有提供 `jumpToToday ` 方法， [跳转至今天](http://calendar.isfeer.com/?id=_4-%E8%B7%B3%E8%BD%AC%E8%87%B3%E6%8C%87%E5%AE%9A%E6%97%A5%E6%9C%9F)
