### ISSUE TITLE
tapDayItem报错

### ISSUE THREAD

**Issue by Pearl140626** [treadpit/wx_calendar#93]
你好，我是在小程序中引用的日历插件，用的功能是单选选中某一天，一直报以下错误：
Cannot set property 'choosed' of undefined;at pages/vip/home page tapDayItem function
TypeError: Cannot set property 'choosed' of undefined
at s.whenSingleSelect (https://usr/app-service.js:5297:6861)
at s.tapDayItem (https://usr/app-service.js:5297:5920)
at s.M (https://lib/WAService.js:1:961298)
at st (https://lib/WAService.js:1:977858)
at https://lib/WAService.js:1:989391
at Function.<anonymous> (https://lib/WAService.js:1:989583)
at https://lib/WAService.js:1:960644
at https://lib/WAService.js:1:480927
at n (https://lib/WAService.js:1:214148)
at Object.S (https://lib/WAService.js:1:1760)

能否帮忙看一下

**Comment by treadpit** [comment]
有复现 demo 么？测了下仓库的 master 分支没问题

**Comment by Pearl140626** [comment]
我试了好多次复现不了，是用户使用的时候报的，小程序后台日志查询看到的同样的错误，每天都有20几个

**Comment by treadpit** [comment]
好的，代码不够健壮的原因，每个用户操作的不可控性或者设备性能差异性，可能会导致某一次点击未获取到当前选择日期，之后去操作这一天的时候抛错了
