### ISSUE TITLE
执行切换周视图方法switchView('week')，报如下错误

### ISSUE THREAD

**Issue by hanyangzao** [treadpit/wx_calendar#94]
`VM6054:1 thirdScriptError
Cannot read property 'todoText' of undefined; [Component] Event Handler Error @ pages/calendar/calendar#bound onChangeView
TypeError: Cannot read property 'todoText' of undefined
    at http://127.0.0.1:10825/appservice/components/calendar/main.js:788:50
    at Array.forEach (<anonymous>)
    at Object.initSelectedDay (http://127.0.0.1:10825/appservice/components/calendar/main.js:779:14)
    at Object.selectedDayWeekAllDays (http://127.0.0.1:10825/appservice/components/calendar/main.js:1017:17)
    at Object.switchWeek (http://127.0.0.1:10825/appservice/components/calendar/main.js:1043:12)
    at Object.switchView (http://127.0.0.1:10825/appservice/components/calendar/main.js:1163:8)
    at z.onChangeView (http://127.0.0.1:10825/appservice/pages/calendar/calendar.js:55:19)
    at Object.r.safeCallback (http://127.0.0.1:10825/appservice/__dev__/WAService.js:1:746848)
    at http://127.0.0.1:10825/appservice/__dev__/WAService.js:1:887706
    at f (http://127.0.0.1:10825/appservice/__dev__/WAService.js:1:890945)
console.error @ VM6054:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
r.safeCallback @ WAService.js:1
r.call @ WAService.js:1
t.message @ WAService.js:1
r.safeCallback @ WAService.js:1
(anonymous) @ WAService.js:1
f @ WAService.js:1
(anonymous) @ WAService.js:1
n @ WAService.js:1
e @ appservice?t=1553349745450:4316
r.registerCallback.t @ appservice?t=1553349745450:4316
l.forEach.t @ appservice?t=1553349745450:4316
(anonymous) @ appservice?t=1553349745450:4316
s.onmessage @ appservice?t=1553349745450:4316`

**Comment by yinhao123** [comment]
I had met this question,thanks you fixed it.
